# Generated by Django 5.0.1 on 2024-01-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.CharField(default='Default doctor', max_length=255),
        ),
    ]
